# Generated by Django 4.2.6 on 2023-11-24 12:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credits', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('general', 'General'), ('specialized', 'Specialized'), ('core', 'Core'), ('optional', 'Optional')], max_length=11)),
                ('co_requisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_courses', to='management.course')),
                ('pre_requisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_courses', to='management.course')),
            ],
        ),
        migrations.CreateModel(
            name='DeleteTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=8)),
                ('student_comment', models.TextField()),
                ('educational_deputy_comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_condition', models.CharField(choices=[('failed', 'Failed'), ('passed', 'Passed')], max_length=6)),
                ('student_grade', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.course')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('units', models.IntegerField()),
                ('stage', models.CharField(choices=[('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PHD')], max_length=9)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='management.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('expertise', models.CharField(blank=True, max_length=250, null=True)),
                ('rank', models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('assistant_professor', 'Assistant Professor'), ('associate_professor', 'Associate Professor'), ('full_professor', 'Full Professor')], max_length=20, null=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='management.major')),
                ('past_courses', models.ManyToManyField(blank=True, to='management.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='management.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('entrance_year', models.IntegerField()),
                ('entrance_term', models.CharField(choices=[('Mehr', 'Mehr'), ('Bahman', 'Bahman')], max_length=6)),
                ('military_status', models.CharField(choices=[('permanent_exemption', 'Permanent Exemption'), ('education_exemption', 'Education Exemption'), ('end_of_service', 'End of Service'), ('included', 'Included')], max_length=20)),
                ('courses', models.ManyToManyField(blank=True, through='management.Enrollment', to='management.course')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('take_course_start_time', models.DateTimeField(blank=True, null=True)),
                ('take_course_end_time', models.DateTimeField(blank=True, null=True)),
                ('class_start_time', models.DateTimeField(blank=True, null=True)),
                ('class_end_time', models.DateTimeField(blank=True, null=True)),
                ('fix_course_start_time', models.DateTimeField(blank=True, null=True)),
                ('fix_course_end_time', models.DateTimeField(blank=True, null=True)),
                ('emergency_removal_end_time', models.DateTimeField(blank=True, null=True)),
                ('exam_start_time', models.DateTimeField(blank=True, null=True)),
                ('term_end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date_time', models.DateTimeField()),
                ('exam_date_time', models.DateTimeField()),
                ('exam_site', models.CharField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.course')),
                ('professors', models.ManyToManyField(to='management.professor')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.term')),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='courses',
            field=models.ManyToManyField(blank=True, through='management.TermCourse', to='management.course'),
        ),
        migrations.AddField(
            model_name='term',
            name='professors',
            field=models.ManyToManyField(blank=True, to='management.professor'),
        ),
        migrations.AddField(
            model_name='term',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='terms', to='management.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_terms',
            field=models.ManyToManyField(blank=True, through='management.DeleteTerm', to='management.term'),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='management.major'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='management.faculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='management.professor'),
        ),
        migrations.CreateModel(
            name='ITManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.student'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='taken_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.term'),
        ),
        migrations.AddField(
            model_name='deleteterm',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_terms', to='management.student'),
        ),
        migrations.AddField(
            model_name='deleteterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_terms', to='management.term'),
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ManyToManyField(related_name='courses', to='management.faculty'),
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='assistant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('major', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.major')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.faculty')),
            ],
        ),
    ]
