# Generated by Django 4.2.6 on 2023-11-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitselection', '0003_enrollment'),
        ('management', '0002_remove_enrollment_course_remove_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, through='unitselection.Enrollment', to='management.course'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
