# Generated by Django 4.2.6 on 2023-11-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('unitselection', '0004_alter_addandremove_added_term_course_id_and_more'),
        ('assessment', '0002_alter_graderevisionrequest_course'),
        ('management', '0003_alter_student_courses_delete_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='termcourse',
            name='professors',
        ),
        migrations.RemoveField(
            model_name='termcourse',
            name='term',
        ),
        migrations.AlterField(
            model_name='professor',
            name='past_courses',
            field=models.ManyToManyField(blank=True, to='academic.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, through='unitselection.Enrollment', to='academic.course'),
        ),
        migrations.AlterField(
            model_name='term',
            name='courses',
            field=models.ManyToManyField(blank=True, through='academic.TermCourse', to='academic.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='TermCourse',
        ),
    ]
