version: '3.8'

services:
  pyveng-db:
    container_name: pyveng-db
    image: postgres:14
    restart: unless-stopped
    volumes:
      - pyveng-db:/var/lib/postgresql/pyveng-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 5s
      retries: 5

  pyveng-api:
    container_name: pyveng-api
    build: .
    restart: unless-stopped
    depends_on:
      pyveng-db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pyveng-db:
    driver: local
