from .course import CourseSerializer, CourseReportSerializer, TermCourseSerializer
from .student import StudentUpdateStudentSerializer, AssistantUpdateStudentSerializer, StudentAllowedCoursesSerializer
from .enrollment import StudentCoursesReportSerializer
from .professor import ProfessorUpdateProfessorSerializer,AssistantUpdateProfessorSerializer
