# Generated by Django 4.2.6 on 2023-11-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=8)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_units', to='management.student')),
                ('term_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_units', to='management.termcourse')),
            ],
        ),
        migrations.CreateModel(
            name='AddAndRemove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=8)),
                ('added_term_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_courses', to='management.termcourse')),
                ('removed_term_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_courses', to='management.termcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_and_removes', to='management.student')),
            ],
        ),
    ]
