# Generated by Django 4.2.6 on 2023-11-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_enrollment_course_remove_enrollment_student_and_more'),
        ('unitselection', '0002_studyenrollmentrequest_emergencycoursedroprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_condition', models.CharField(choices=[('failed', 'Failed'), ('passed', 'Passed')], max_length=6)),
                ('student_grade', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.student')),
                ('taken_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.term')),
            ],
        ),
    ]
