# Generated by Django 4.2.6 on 2023-11-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('unitselection', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addandremove',
            name='added_term_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_courses', to='academic.termcourse'),
        ),
        migrations.AlterField(
            model_name='addandremove',
            name='removed_term_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_courses', to='academic.termcourse'),
        ),
        migrations.AlterField(
            model_name='emergencycoursedroprequest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_course_drop_request', to='academic.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.course'),
        ),
        migrations.AlterField(
            model_name='selectunit',
            name='term_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_units', to='academic.termcourse'),
        ),
    ]
