# Generated by Django 4.2.6 on 2023-11-24 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0003_alter_student_courses_delete_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credits', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('general', 'General'), ('specialized', 'Specialized'), ('core', 'Core'), ('optional', 'Optional')], max_length=11)),
                ('co_requisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_courses', to='academic.course')),
                ('pre_requisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_courses', to='academic.course')),
                ('schools', models.ManyToManyField(related_name='courses', to='management.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='TermCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date_time', models.DateTimeField()),
                ('exam_date_time', models.DateTimeField()),
                ('exam_site', models.CharField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(250)])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.course')),
                ('professors', models.ManyToManyField(to='management.professor')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.term')),
            ],
        ),
    ]
