# Generated by Django 4.2.6 on 2023-11-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('professor', 'professor'), ('assistant', 'assistant')], default='It-manager'),
            preserve_default=False,
        ),
    ]
