# Generated by Django 4.2.6 on 2023-11-08 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
