# Generated by Django 4.2.6 on 2023-11-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_user_id_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Assistant', 'Assistant'), ('It-manager', 'It-manager')]),
        ),
    ]
