# Generated by Django 4.2.6 on 2023-11-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_national_code_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Assistant', 'Assistant'), ('It-manager', 'It-manager')], verbose_name='Role'),
        ),
    ]
