# Generated by Django 4.2.6 on 2023-11-15 12:15
from django.contrib.auth.models import Group
from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name="IT Manager")
    Group.objects.get_or_create(name="Assistance")
    Group.objects.get_or_create(name="Professor")
    Group.objects.get_or_create(name="Student")


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['IT Manager', 'Assistance', 'Professor', 'Student']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_user_role_alter_user_gender'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups),
    ]
