# Generated by Django 4.2.6 on 2023-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Assistant', 'Assistant'), ('IT Manager', 'IT Manager')], verbose_name='role'),
        ),
    ]
