# Generated by Django 4.2.6 on 2023-11-11 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credits', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('general', 'General'), ('specialized', 'Specialized'), ('core', 'Core'), ('optional', 'Optional')])),
                ('co_requisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_courses', to='university.course')),
                ('pre_requisites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_courses', to='university.course')),
            ],
        ),
        migrations.CreateModel(
            name='TermCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date_time', models.DateTimeField()),
                ('exam_date_time', models.DateTimeField()),
                ('exam_site', models.CharField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(250)])),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.course')),
            ],
        ),
    ]
