# Generated by Django 4.2.6 on 2023-11-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalDeputy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('units', models.IntegerField()),
                ('stage', models.CharField(choices=[('associate', 0), ('bachelor', 1), ('master', 2), ('phd', 3)])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField()),
                ('entrance_term', models.CharField(choices=[('Mehr', 1), ('Bahman', 2)])),
                ('military_status', models.CharField(choices=[('permanent_exemption', 0), ('education_exemption', 1), ('end_of_service', 2), ('included', 3)])),
                ('sanavat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('take_course_start_time', models.DateTimeField(blank=True, null=True)),
                ('take_course_end_time', models.DateTimeField(blank=True, null=True)),
                ('class_start_time', models.DateTimeField(blank=True, null=True)),
                ('class_end_time', models.DateTimeField(blank=True, null=True)),
                ('fix_course_start_time', models.DateTimeField(blank=True, null=True)),
                ('fix_course_end_time', models.DateTimeField(blank=True, null=True)),
                ('emergency_removal_end_time', models.DateTimeField(blank=True, null=True)),
                ('exam_start_time', models.DateTimeField(blank=True, null=True)),
                ('term_end_time', models.DateTimeField(blank=True, null=True)),
                ('students', models.ManyToManyField(blank=True, null=True, to='university.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_condition', models.CharField(max_length=128)),
                ('student_grade', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.student')),
                ('taken_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.term')),
            ],
        ),
    ]
