# Generated by Django 4.2.6 on 2023-11-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='major',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='university.major'),
        ),
        migrations.AlterField(
            model_name='assistant',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='university.school'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professors', to='university.major'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professors', to='university.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='university.major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='university.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='university.professor'),
        ),
    ]
